{ config, lib, pkgs, ... }: {

  boot.cleanTmpDir = true;

  boot.initrd = {
    availableKernelModules =
      # Generated by `nixos-generate-config`.
      ["ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
    kernelModules = [
      "zfs"
    ];
    supportedFilesystems = [
      "vfat"
      "zfs"
    ];
  };

  boot.kernel = {
    sysctl = {
      "vm.overcommit_memory" = lib.mkIf
        (config.c74d-params.hardware.memory.main.gigabytes >= 2)
        2;
    };
  };

  boot.kernelModules =
    # Generated by `nixos-generate-config`.
    ["kvm-intel"];

  boot.loader = {
    systemd-boot = {
      # Generated by `nixos-generate-config`.
      enable = true;
    };
    efi = {
      # Generated by `nixos-generate-config`.
      canTouchEfiVariables = true;
    };
  };

  # Per <https://nixos.org/wiki/ZFS_on_NixOS>.
  boot.supportedFilesystems = [
    "vfat"
    "zfs"
  ];

  boot.tmpOnTmpfs = true;

  boot.zfs = {
    forceImportAll = false;
    forceImportRoot = false;
  };

}
